version: "3"
services:
  app:
    build:
      context: .
    environment:
      AWS_REGION: ${AWS_REGION:-us-west-2}
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}" # add to .env file (DO NOT CHECK IN)
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}" # add to .env file (DO NOT CHECK IN)
      COGNITO_USER_POOL_ID: ${COGNITO_USER_POOL_ID:-us-west-2_CGd9Wq136}
      S3_BUCKET_URI: ${S3_BUCKET_URI:-sinopia-cognito-development}
    command: bin/backup
